export const itemImages = {
  'Normal Log': 'https://cdn.melvor.net/core/v018/assets/media/bank/logs_normal.png?2',
  'Oak Log': 'https://cdn.melvor.net/core/v018/assets/media/bank/logs_oak.png?2',
  'Willow Log': 'https://cdn.melvor.net/core/v018/assets/media/bank/logs_willow.png?2',
  'Teak Log': 'https://cdn.melvor.net/core/v018/assets/media/bank/logs_teak.png?2',
  'Maple Log': 'https://cdn.melvor.net/core/v018/assets/media/bank/logs_maple.png?2',
  'Mahogany Log': 'https://cdn.melvor.net/core/v018/assets/media/bank/logs_mahogany.png?2',
  'Yew Log': 'https://cdn.melvor.net/core/v018/assets/media/bank/logs_yew.png?2',
  'Magic Log': 'https://cdn.melvor.net/core/v018/assets/media/bank/logs_magic.png?2',
  'Redwood Log': 'https://cdn.melvor.net/core/v018/assets/media/bank/logs_redwood.png?2',
  'Rune Essence': 'https://cdn.melvor.net/core/v018/assets/media/bank/rune_essence.png',
  'Copper Ore': 'https://cdn.melvor.net/core/v018/assets/media/bank/ore_copper.png',
  'Tin Ore': 'https://cdn.melvor.net/core/v018/assets/media/bank/ore_tin.png',
  'Iron Ore': 'https://cdn.melvor.net/core/v018/assets/media/bank/ore_iron.png',
  'Coal Ore': 'https://cdn.melvor.net/core/v018/assets/media/bank/ore_coal.png',
  'Silver Ore': 'https://cdn.melvor.net/core/v018/assets/media/bank/ore_silver.png',
  'Gold Ore': 'https://cdn.melvor.net/core/v018/assets/media/bank/ore_gold.png',
  'Mithril Ore': 'https://cdn.melvor.net/core/v018/assets/media/bank/ore_mithril.png',
  'Adamantite Ore': 'https://cdn.melvor.net/core/v018/assets/media/bank/ore_adamantite.png',
  'Runite Ore': 'https://cdn.melvor.net/core/v018/assets/media/bank/ore_runite.png',
  'Dragonite Ore': 'https://cdn.melvor.net/core/v018/assets/media/bank/ore_dragonite.png',
}

export const miningImages = {
  'Rune Essence': 'https://cdn.melvor.net/core/v018/assets/media/bank/rune_essence.png',
  'Copper Rock': 'https://cdn.melvor.net/core/v018/assets/media/skills/mining/rock_copper.svg',
  'Tin Rock': 'https://cdn.melvor.net/core/v018/assets/media/skills/mining/rock_tin.svg',
  'Iron Rock': 'https://cdn.melvor.net/core/v018/assets/media/skills/mining/rock_iron.svg',
  'Gold Rock': 'https://cdn.melvor.net/core/v018/assets/media/skills/mining/rock_gold.svg',
}